config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  resources :posts, only: [:new, :create, :show] do
    resources :comments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    render partial: 'new'
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.create(comment_params)
    render json: comment
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    render partial: 'new'
  end

  def create
    post = Post.create(post_params)
    render json: post
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_new.html.erb
<%= content_tag 'div', class: 'card', data: {target: 'comment.newCommentForm', action: 'ajax:success->comment#prependComment'} do %>
  <%= content_tag 'div', class: 'card-body' do %>
    <%= form_with model: @comment, url: post_comments_path do |f| %>
      <%= content_tag 'div', class: 'mb-3' do %>
        <%= f.label :body, 'Your comment', class: 'form-label' %>
        <%= f.text_area :body, class: 'form-control' %>
      <% end %>
      <%= f.button type: 'submit', class: 'btn btn-primary' %>
      <%= f.button 'Cancel', type: 'button', class: 'btn btn-danger', data: {action: 'click->comment#hideForm'} %>
    <% end %>
  <% end %>
<% end %>

app/views/homepage/index.html.erb
<div class="container" data-controller="post">
  <h1>All Posts</h1>
  <%= content_tag 'div', data: {target: 'post.newPost'} do %>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-primary mb-3', data: {target: 'post.newButton', action: 'ajax:success->post#newPostForm', remote: true} %>
  <% end %>
  <%= content_tag 'div', data: {target: 'post.postContainer'} do %>
    <% @posts.each do |post| %>
      <%= link_to post.title, post, class: 'd-block' %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_new.html.erb
<%= content_tag 'div', class: 'card', data: {target: 'post.newPostForm', action: 'ajax:success->post#prependPost'} do %>
  <%= content_tag 'div', class: 'card-body' do %>
    <%= form_with model: @post do |f| %>
      <%= content_tag 'div', class: 'mb-3' do %>
        <%= f.label :title, 'Post title', class: 'form-label' %>
        <%= f.text_field :title, class: 'form-control' %>
      <% end %>
      <%= content_tag 'div', class: 'mb-3' do %>
        <%= f.label :content, 'Post content', class: 'form-label' %>
        <%= f.text_area :content, class: 'form-control' %>
      <% end %>
      <%= f.button type: 'submit', class: 'btn btn-primary' %>
      <%= f.button 'Cancel', type: 'button', class: 'btn btn-danger', data: {action: 'click->post#hideForm'} %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<div class="container" data-controller="comment">
  <%= content_tag 'h1', @post.title %>
  <%= content_tag 'div', class: 'card' do %>
    <%= content_tag 'div', class: 'card-body' do %>
      <%= content_tag 'p', @post.content %>
      <%= content_tag 'div', data: {target: 'comment.container'} do %>
        <%= link_to 'Add Comment', new_post_comment_path(@post), class: 'btn btn-primary', id: 'new-comment', remote: true, data: {action: 'ajax:success->comment#newComment', target: 'comment.newButton'} %>
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag 'div', id: 'comment-container' do %>
    <%= content_tag 'h2', 'Comments', class: 'mt-3' %>
    <%= content_tag 'div', data: {target: 'comment.commentList'} do %>
      <% @comments.each do |comment| %>
        <%= content_tag 'p', comment.body %>
      <% end %>
    <% end %>
  <% end %>
</div>